export const CREATE_ENGINESGROUP_REQUEST = 'CREATE_ENGINESGROUP_REQUEST';
export const CREATE_ENGINESGROUP_SUCCESS = 'CREATE_ENGINESGROUP_SUCCESS';
export const CREATE_ENGINESGROUP_ERROR = 'CREATE_ENGINESGROUP_ERROR';
export const EDIT_ENGINESGROUP_REQUEST = 'EDIT_ENGINESGROUP_REQUEST';
export const EDIT_ENGINESGROUP_SUCCESS = 'EDIT_ENGINESGROUP_SUCCESS';
export const EDIT_ENGINESGROUP_ERROR = 'EDIT_ENGINESGROUP_ERROR';
export const RESET_ENGINESGROUP_SAVE_ERROR = 'RESET_ENGINESGROUP_SAVE_ERROR';
export const RESET_ENGINESGROUP_SAVE_SUCCESS = 'RESET_ENGINESGROUP_SAVE_SUCCESS';
