export const SAVE_CREATE_SCOPE_REQUEST = 'SAVE_CREATE_SCOPE_REQUEST';
export const SAVE_CREATE_SCOPE_SUCCESS = 'SAVE_CREATE_SCOPE_SUCCESS';
export const SAVE_CREATE_SCOPE_ERROR = 'SAVE_CREATE_SCOPE_ERROR';
export const SAVE_EDIT_SCOPE_REQUEST = 'SAVE_EDIT_SCOPE_REQUEST';
export const SAVE_EDIT_SCOPE_SUCCESS = 'SAVE_EDIT_SCOPE_SUCCESS';
export const SAVE_EDIT_SCOPE_ERROR = 'SAVE_EDIT_SCOPE_ERROR';
export const RESET_SCOPE_SAVE_ERROR = 'RESET_SCOPE_SAVE_ERROR';
export const RESET_SCOPE_SAVE_SUCCESS = 'RESET_SCOPE_SAVE_SUCCESS';
